application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      my-app:
        license: Apache-2.0
        actions:
          publish-events:
            function: actions/publish-events/index.js
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
              providerId: $PROVIDER_ID
              eventCode: $EVENT_CODE
              client_id: $CLIENT_ID
              client_secret: $CLIENT_SECRET
              technical_account_email: $TECH_ACCOUNT_EMAIL
              technical_account_id: $TECH_ACCOUNT_ID
              ims_org_id: $IMS_ORG_ID
              private_key: $PRIVATE_KEY
            annotations:
              final: true
          triggers:
            everyMin:
              feed: /whisk.system/alarms/interval
              inputs:
                minutes: 1
          rules:
            everyMinRule:
              trigger: everyMin
              action: publish-events
